/*==============================================================
Object Name : AEROSPACE_PARTS_TARGET
Purpose     : DDL for the target table storing transformed,
              deduplicated, and SCD Type 1 managed aerospace
              parts inventory data with derived RISK_SCORE.
Generated By: SDLC_AGENT
Generated Date: 2026-09-10
==============================================================*/

---------------------------------------------------------
-- SECTION 1
-- Purpose: Create target table AEROSPACE_PARTS_TARGET with
--          all business columns, derived RISK_SCORE column,
--          soft-delete support, and ETL audit columns.
---------------------------------------------------------

CREATE TABLE IF NOT EXISTS GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET (
    PART_NUMBER             VARCHAR(100)    NOT NULL,
    PART_NAME               VARCHAR(255),
    MANUFACTURER            VARCHAR(255),
    CATEGORY                VARCHAR(100),
    SUBCATEGORY             VARCHAR(100),
    UNIT_PRICE_USD          NUMBER(18,2),
    WEIGHT_KG               NUMBER(18,4),
    LEAD_TIME_DAYS          NUMBER(10,0),
    CERTIFICATION_STATUS    VARCHAR(50),
    LIFECYCLE_STATUS        VARCHAR(50),
    INSTALLATION_DATE       DATE,
    LAST_INSPECTION_DATE    DATE,
    WAREHOUSE_LOCATION      VARCHAR(100),
    SUPPLIER_ID             VARCHAR(100),
    SUPPLIER_NAME           VARCHAR(255),
    COUNTRY_OF_ORIGIN       VARCHAR(100),
    QUANTITY_ON_HAND        NUMBER(18,0),
    REORDER_POINT           NUMBER(18,0),
    REORDER_QUANTITY        NUMBER(18,0),
    UNIT_OF_MEASURE         VARCHAR(50),
    HAZMAT_FLAG             VARCHAR(10),
    EXPORT_CONTROL_FLAG     VARCHAR(10),
    NOTES                   VARCHAR(4000),
    RISK_SCORE              VARCHAR(50),
    UPDATED_AT              TIMESTAMP_NTZ,
    CREATED_AT              TIMESTAMP_NTZ,
    ETL_LOAD_TIMESTAMP      TIMESTAMP_NTZ,
    CONSTRAINT PK_AEROSPACE_PARTS_TARGET PRIMARY KEY (PART_NUMBER)
);