/*==============================================================
Object Name : ETL_RECONCILIATION_LOG
Purpose     : DDL for the reconciliation audit log table that
              captures pipeline run metrics, row counts, status,
              and error details for every execution of
              SP_LOAD_AEROSPACE_PARTS_SCD1.
Generated By: SDLC_AGENT
Generated Date: 2026-09-10
==============================================================*/

---------------------------------------------------------
-- SECTION 1
-- Purpose: Create ETL_RECONCILIATION_LOG table to store
--          one audit record per pipeline execution with
--          full run metrics and status tracking.
---------------------------------------------------------

CREATE TABLE IF NOT EXISTS GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG (
    LOG_ID                  NUMBER AUTOINCREMENT PRIMARY KEY,
    PIPELINE_NAME           VARCHAR(255)    NOT NULL,
    RUN_START_TIMESTAMP     TIMESTAMP_NTZ   NOT NULL,
    RUN_END_TIMESTAMP       TIMESTAMP_NTZ,
    LOAD_TYPE               VARCHAR(20),
    WATERMARK_USED          TIMESTAMP_NTZ,
    SOURCE_ROW_COUNT        NUMBER(18,0),
    EXTRACTED_ROW_COUNT     NUMBER(18,0),
    DEDUPLICATED_ROW_COUNT  NUMBER(18,0),
    EXCLUDED_ROW_COUNT      NUMBER(18,0),
    INSERTED_ROW_COUNT      NUMBER(18,0),
    UPDATED_ROW_COUNT       NUMBER(18,0),
    DECOMMISSIONED_ROW_COUNT NUMBER(18,0),
    TARGET_ROW_COUNT        NUMBER(18,0),
    RUN_STATUS              VARCHAR(20),
    ERROR_MESSAGE           VARCHAR(4000),
    CREATED_AT              TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP()
);