/*==============================================================
Object Name : SP_LOAD_AEROSPACE_PARTS_SCD1
Purpose     : Main pipeline stored procedure implementing SCD
              Type 1 load for AEROSPACE_PARTS_TARGET from
              AEROSPACE_PARTS_SOURCE. Handles incremental/full
              load, deduplication, transformation, exclusion,
              RISK_SCORE derivation, soft delete, and
              reconciliation logging.
Generated By: SDLC_AGENT
Generated Date: 2026-09-10
==============================================================*/

---------------------------------------------------------
-- SECTION 1
-- Purpose: Create or replace the main pipeline stored procedure
--          SP_LOAD_AEROSPACE_PARTS_SCD1 with full SCD Type 1
--          logic, transformation rules, and audit logging.
---------------------------------------------------------

CREATE OR REPLACE PROCEDURE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.SP_LOAD_AEROSPACE_PARTS_SCD1()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
DECLARE
    -- -------------------------------------------------------
    -- Runtime and watermark variables
    -- -------------------------------------------------------
    V_RUN_START             TIMESTAMP_NTZ;
    V_RUN_END               TIMESTAMP_NTZ;
    V_WATERMARK             TIMESTAMP_NTZ;
    V_LOAD_TYPE             VARCHAR(20);
    V_PIPELINE_NAME         VARCHAR(255);
    V_THREE_YEARS_AGO       DATE;

    -- -------------------------------------------------------
    -- Row count tracking variables
    -- -------------------------------------------------------
    V_SOURCE_ROW_COUNT          NUMBER(18,0);
    V_EXTRACTED_ROW_COUNT       NUMBER(18,0);
    V_DEDUPLICATED_ROW_COUNT    NUMBER(18,0);
    V_EXCLUDED_ROW_COUNT        NUMBER(18,0);
    V_INSERTED_ROW_COUNT        NUMBER(18,0);
    V_UPDATED_ROW_COUNT         NUMBER(18,0);
    V_DECOMMISSIONED_ROW_COUNT  NUMBER(18,0);
    V_TARGET_ROW_COUNT          NUMBER(18,0);
    V_NULL_UPDATED_AT_COUNT     NUMBER(18,0);
    V_NULL_UPDATED_AT_PCT       FLOAT;
    V_NULL_UPDATED_AT_THRESHOLD FLOAT;

    -- -------------------------------------------------------
    -- Result and status variables
    -- -------------------------------------------------------
    V_RESULT                VARCHAR;
    V_LOG_ID                NUMBER(18,0);

BEGIN
    -- -------------------------------------------------------
    -- SECTION 2
    -- Purpose: Initialize runtime variables and pipeline
    --          configuration constants.
    -- -------------------------------------------------------

    V_RUN_START             := CURRENT_TIMESTAMP()::TIMESTAMP_NTZ;
    V_PIPELINE_NAME         := 'SP_LOAD_AEROSPACE_PARTS_SCD1';
    V_THREE_YEARS_AGO       := DATEADD('YEAR', -3, CURRENT_DATE())::DATE;
    V_NULL_UPDATED_AT_THRESHOLD := 0.50;

    V_SOURCE_ROW_COUNT          := 0;
    V_EXTRACTED_ROW_COUNT       := 0;
    V_DEDUPLICATED_ROW_COUNT    := 0;
    V_EXCLUDED_ROW_COUNT        := 0;
    V_INSERTED_ROW_COUNT        := 0;
    V_UPDATED_ROW_COUNT         := 0;
    V_DECOMMISSIONED_ROW_COUNT  := 0;
    V_TARGET_ROW_COUNT          := 0;
    V_NULL_UPDATED_AT_COUNT     := 0;
    V_NULL_UPDATED_AT_PCT       := 0.0;

    -- -------------------------------------------------------
    -- SECTION 3
    -- Purpose: Insert an in-progress reconciliation log entry
    --          at the start of the run to ensure every
    --          execution is tracked even on failure.
    -- -------------------------------------------------------

    INSERT INTO GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG (
        PIPELINE_NAME,
        RUN_START_TIMESTAMP,
        RUN_STATUS,
        CREATED_AT
    )
    VALUES (
        :V_PIPELINE_NAME,
        :V_RUN_START,
        'RUNNING',
        CURRENT_TIMESTAMP()::TIMESTAMP_NTZ
    );

    SELECT MAX(LOG_ID)
    INTO :V_LOG_ID
    FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG
    WHERE PIPELINE_NAME = :V_PIPELINE_NAME
      AND RUN_STATUS    = 'RUNNING'
      AND RUN_START_TIMESTAMP = :V_RUN_START;

    -- -------------------------------------------------------
    -- SECTION 4
    -- Purpose: Determine load type (FULL or INCREMENTAL) by
    --          checking for a prior successful run watermark
    --          in ETL_RECONCILIATION_LOG. On first run or when
    --          no successful run exists, perform a full load.
    -- -------------------------------------------------------

    SELECT MAX(RUN_END_TIMESTAMP)
    INTO :V_WATERMARK
    FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG
    WHERE PIPELINE_NAME = :V_PIPELINE_NAME
      AND RUN_STATUS    = 'SUCCESS';

    IF (V_WATERMARK IS NULL) THEN
        V_LOAD_TYPE := 'FULL';
    ELSE
        V_LOAD_TYPE := 'INCREMENTAL';
    END IF;

    -- -------------------------------------------------------
    -- SECTION 5
    -- Purpose: Count total rows in source and validate
    --          UPDATED_AT completeness. If NULL UPDATED_AT
    --          exceeds the configured threshold, fall back
    --          to a full load per risk mitigation R-003.
    -- -------------------------------------------------------

    SELECT COUNT(*)
    INTO :V_SOURCE_ROW_COUNT
    FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE;

    IF (V_SOURCE_ROW_COUNT > 0) THEN
        SELECT COUNT(*)
        INTO :V_NULL_UPDATED_AT_COUNT
        FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE
        WHERE UPDATED_AT IS NULL;

        V_NULL_UPDATED_AT_PCT := :V_NULL_UPDATED_AT_COUNT / :V_SOURCE_ROW_COUNT;

        IF (V_NULL_UPDATED_AT_PCT > V_NULL_UPDATED_AT_THRESHOLD) THEN
            V_LOAD_TYPE  := 'FULL';
            V_WATERMARK  := NULL;
        END IF;
    END IF;

    -- -------------------------------------------------------
    -- SECTION 6
    -- Purpose: Create a transient staging table to hold the
    --          deduplicated, filtered, and transformed records
    --          extracted from AEROSPACE_PARTS_SOURCE for this
    --          pipeline run. Dropped and recreated each run.
    -- -------------------------------------------------------

    DROP TABLE IF EXISTS GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_STAGE_WORK;

    CREATE TRANSIENT TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_STAGE_WORK AS
    WITH RAW_EXTRACT AS (
        SELECT
            PART_NUMBER,
            PART_NAME,
            MANUFACTURER,
            CATEGORY,
            SUBCATEGORY,
            UNIT_PRICE_USD,
            WEIGHT_KG,
            LEAD_TIME_DAYS,
            CERTIFICATION_STATUS,
            LIFECYCLE_STATUS,
            INSTALLATION_DATE,
            LAST_INSPECTION_DATE,
            WAREHOUSE_LOCATION,
            SUPPLIER_ID,
            SUPPLIER_NAME,
            COUNTRY_OF_ORIGIN,
            QUANTITY_ON_HAND,
            REORDER_POINT,
            REORDER_QUANTITY,
            UNIT_OF_MEASURE,
            HAZMAT_FLAG,
            EXPORT_CONTROL_FLAG,
            NOTES,
            UPDATED_AT,
            CREATED_AT
        FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE
        WHERE (
            :V_LOAD_TYPE = 'FULL'
            OR (
                :V_LOAD_TYPE = 'INCREMENTAL'
                AND UPDATED_AT > :V_WATERMARK
            )
        )
        AND PART_NUMBER IS NOT NULL
    ),
    DEDUPED AS (
        SELECT
            PART_NUMBER,
            PART_NAME,
            MANUFACTURER,
            CATEGORY,
            SUBCATEGORY,
            UNIT_PRICE_USD,
            WEIGHT_KG,
            LEAD_TIME_DAYS,
            CERTIFICATION_STATUS,
            LIFECYCLE_STATUS,
            INSTALLATION_DATE,
            LAST_INSPECTION_DATE,
            WAREHOUSE_LOCATION,
            SUPPLIER_ID,
            SUPPLIER_NAME,
            COUNTRY_OF_ORIGIN,
            QUANTITY_ON_HAND,
            REORDER_POINT,
            REORDER_QUANTITY,