/*==============================================================
Object Name    : DDL_SETUP
Purpose        : Create all required tables, file formats, and
                 stages for the customer and order data pipeline
                 in IDEA_2_DB.PUBLIC schema.
Generated By   : SDLC_DEVELOPER
==============================================================*/

---------------------------------------------------------
-- SECTION 1
-- Purpose: Create CSV File Format for staged data ingestion
---------------------------------------------------------

-- Create CSV file format for loading customer and order data
-- Purpose: Define parsing rules for CSV files loaded from Snowflake stage
CREATE FILE FORMAT IF NOT EXISTS IDEA_2_DB.PUBLIC.CSV_FILE_FORMAT
    TYPE                        = 'CSV'
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER                 = 1
    NULL_IF                     = ('NULL', 'null', '')
    EMPTY_FIELD_AS_NULL         = TRUE
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;

---------------------------------------------------------
-- SECTION 2
-- Purpose: Create CUSTOMER staging and target table
---------------------------------------------------------

-- Create CUSTOMER table to hold raw ingested customer records
-- Purpose: Persistent landing table for customer CSV data loaded from stage
CREATE TABLE IF NOT EXISTS IDEA_2_DB.PUBLIC.CUSTOMER (
    CUSTID    VARCHAR(50),
    NAME      VARCHAR(255),
    EMAILID   VARCHAR(255),
    REGION    VARCHAR(100)
);

---------------------------------------------------------
-- SECTION 3
-- Purpose: Create ORDER target table
---------------------------------------------------------

-- Create ORDER table to hold raw ingested order records
-- Purpose: Persistent landing table for order CSV data loaded from stage
CREATE TABLE IF NOT EXISTS IDEA_2_DB.PUBLIC."order" (
    ORDERID       VARCHAR(50),
    CUSTID        VARCHAR(50),
    ITEMNAME      VARCHAR(255),
    PRICEPERUNIT  NUMBER(18,2),
    QTY           NUMBER(18,2),
    ORDER_DATE    DATE,
    STARTDATE     DATE,
    ENDDATE       DATE,
    ISACTIVE      VARCHAR(10)
);

---------------------------------------------------------
-- SECTION 4
-- Purpose: Create ORDER SUMMARY table for joined/transformed data
---------------------------------------------------------

-- Create ORDERSUMMARY table to hold joined customer and order data
-- Purpose: Stores enriched order records with customer name and computed total amount
CREATE TABLE IF NOT EXISTS IDEA_2_DB.PUBLIC.ORDERSUMMARY (
    ORDERID       VARCHAR(50),
    CUSTID        VARCHAR(50),
    NAME          VARCHAR(255),
    ITEMNAME      VARCHAR(255),
    PRICEPERUNIT  NUMBER(18,2),
    QTY           NUMBER(18,2),
    TOTALAMOUNT   NUMBER(18,2),
    ORDER_DATE    DATE,
    STARTDATE     DATE,
    ENDDATE       DATE,
    ISACTIVE      VARCHAR(10)
);

---------------------------------------------------------
-- SECTION 5
-- Purpose: Create CUSTOMER SCD Type 2 table
---------------------------------------------------------

-- Create CUSTOMER_SCD2 table to track historical changes in customer records
-- Purpose: Implements SCD Type 2 pattern with effective date range and current flag
CREATE TABLE IF NOT EXISTS IDEA_2_DB.PUBLIC.CUSTOMER_SCD2 (
    SCD2_KEY        NUMBER AUTOINCREMENT PRIMARY KEY,
    CUSTID          VARCHAR(50),
    NAME            VARCHAR(255),
    EMAILID         VARCHAR(255),
    REGION          VARCHAR(100),
    IS_CURRENT      BOOLEAN,
    EFFECTIVE_FROM  DATE,
    EFFECTIVE_TO    DATE
);

---------------------------------------------------------
-- SECTION 6
-- Purpose: Create CUSTOMER AGGREGATE SPEND table
---------------------------------------------------------

-- Create CUSTOMERAGGREGATESPEND table to hold aggregated spend data
-- Purpose: Stores daily aggregated total spend per customer name for reporting
CREATE TABLE IF NOT EXISTS IDEA_2_DB.PUBLIC.CUSTOMERAGGREGATESPEND (
    NAME          VARCHAR(255),
    ORDER_DATE    DATE,
    TOTALSPEND    NUMBER(18,2)
);