/*==============================================================
Object Name    : INGEST_LOAD
Purpose        : Load customer and order CSV data from Snowflake
                 internal stage into the CUSTOMER and ORDER
                 landing tables in IDEA_2_DB.PUBLIC.
Generated By   : SDLC_DEVELOPER
==============================================================*/

---------------------------------------------------------
-- SECTION 1
-- Purpose: Truncate landing tables before fresh load
---------------------------------------------------------

-- Truncate CUSTOMER table before reloading from stage
-- Purpose: Ensure idempotent daily load by clearing prior data before COPY INTO
TRUNCATE TABLE IDEA_2_DB.PUBLIC.CUSTOMER;

-- Truncate ORDER table before reloading from stage
-- Purpose: Ensure idempotent daily load by clearing prior data before COPY INTO
TRUNCATE TABLE IDEA_2_DB.PUBLIC."order";

---------------------------------------------------------
-- SECTION 2
-- Purpose: Load customer data from stage into CUSTOMER table
---------------------------------------------------------

-- Load customer CSV data from Snowflake stage into CUSTOMER table
-- Purpose: Ingest raw customer records (CUSTID, NAME, EMAILID, REGION) from stage path
COPY INTO IDEA_2_DB.PUBLIC.CUSTOMER (
    CUSTID,
    NAME,
    EMAILID,
    REGION
)
FROM @IDEA_2_DB.PUBLIC.CSV_FILE_FORMAT/customerdata
FILE_FORMAT = (
    FORMAT_NAME                    = IDEA_2_DB.PUBLIC.CSV_FILE_FORMAT
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
)
ON_ERROR = CONTINUE;

---------------------------------------------------------
-- SECTION 3
-- Purpose: Load order data from stage into ORDER table
---------------------------------------------------------

-- Load order CSV data from Snowflake stage into ORDER table
-- Purpose: Ingest raw order records (9 columns) from stage path into landing table
COPY INTO IDEA_2_DB.PUBLIC."order" (
    ORDERID,
    CUSTID,
    ITEMNAME,
    PRICEPERUNIT,
    QTY,
    ORDER_DATE,
    STARTDATE,
    ENDDATE,
    ISACTIVE
)
FROM @IDEA_2_DB.PUBLIC.CSV_FILE_FORMAT/orderdata
FILE_FORMAT = (
    FORMAT_NAME                    = IDEA_2_DB.PUBLIC.CSV_FILE_FORMAT
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
)
ON_ERROR = CONTINUE;