/*==============================================================
Object Name    : TRANSFORM_CLEAN
Purpose        : Remove null and duplicate records from the
                 CUSTOMER and ORDER landing tables to ensure
                 data quality before downstream transformations.
Generated By   : SDLC_DEVELOPER
==============================================================*/

---------------------------------------------------------
-- SECTION 1
-- Purpose: Remove null records from CUSTOMER table
---------------------------------------------------------

-- Delete rows with null values in key CUSTOMER columns
-- Purpose: Eliminate incomplete customer records that would cause join failures or bad aggregations
DELETE FROM IDEA_2_DB.PUBLIC.CUSTOMER
WHERE CUSTID   IS NULL
   OR NAME     IS NULL
   OR EMAILID  IS NULL
   OR REGION   IS NULL;

---------------------------------------------------------
-- SECTION 2
-- Purpose: Remove null records from ORDER table
---------------------------------------------------------

-- Delete rows with null values in key ORDER columns
-- Purpose: Eliminate incomplete order records that would produce incorrect totals or join mismatches
DELETE FROM IDEA_2_DB.PUBLIC."order"
WHERE ORDERID      IS NULL
   OR CUSTID       IS NULL
   OR ITEMNAME     IS NULL
   OR PRICEPERUNIT IS NULL
   OR QTY          IS NULL
   OR ORDER_DATE   IS NULL;

---------------------------------------------------------
-- SECTION 3
-- Purpose: Remove duplicate records from CUSTOMER table
---------------------------------------------------------

-- Delete duplicate CUSTOMER records keeping the first occurrence per CUSTID
-- Purpose: Ensure one canonical customer record per CUSTID using ROW_NUMBER deduplication
DELETE FROM IDEA_2_DB.PUBLIC.CUSTOMER
WHERE (CUSTID, NAME, EMAILID, REGION) IN (
    SELECT CUSTID, NAME, EMAILID, REGION
    FROM (
        SELECT
            CUSTID,
            NAME,
            EMAILID,
            REGION,
            ROW_NUMBER() OVER (PARTITION BY CUSTID ORDER BY CUSTID) AS RN
        FROM IDEA_2_DB.PUBLIC.CUSTOMER
    ) DEDUP
    WHERE RN > 1
);

---------------------------------------------------------
-- SECTION 4
-- Purpose: Remove duplicate records from ORDER table
---------------------------------------------------------

-- Delete duplicate ORDER records keeping the first occurrence per ORDERID
-- Purpose: Ensure one canonical order record per ORDERID using ROW_NUMBER deduplication
DELETE FROM IDEA_2_DB.PUBLIC."order"
WHERE (ORDERID, CUSTID, ITEMNAME, PRICEPERUNIT, QTY, ORDER_DATE, STARTDATE, ENDDATE, ISACTIVE) IN (
    SELECT ORDERID, CUSTID, ITEMNAME, PRICEPERUNIT, QTY, ORDER_DATE, STARTDATE, ENDDATE, ISACTIVE
    FROM (
        SELECT
            ORDERID,
            CUSTID,
            ITEMNAME,
            PRICEPERUNIT,
            QTY,
            ORDER_DATE,
            STARTDATE,
            ENDDATE,
            ISACTIVE,
            ROW_NUMBER() OVER (PARTITION BY ORDERID ORDER BY ORDERID) AS RN
        FROM IDEA_2_DB.PUBLIC."order"
    ) DEDUP
    WHERE RN > 1
);