/*==============================================================
Object Name    : TRANSFORM_ORDERSUMMARY
Purpose        : Join cleaned CUSTOMER and ORDER data on CUSTID,
                 compute TOTALAMOUNT (PRICEPERUNIT * QTY), and
                 load the enriched records into ORDERSUMMARY table.
Generated By   : SDLC_DEVELOPER
==============================================================*/

---------------------------------------------------------
-- SECTION 1
-- Purpose: Truncate ORDERSUMMARY before reloading joined data
---------------------------------------------------------

-- Truncate ORDERSUMMARY table to prepare for fresh daily load
-- Purpose: Ensure idempotent daily refresh of the order summary dataset
TRUNCATE TABLE IDEA_2_DB.PUBLIC.ORDERSUMMARY;

---------------------------------------------------------
-- SECTION 2
-- Purpose: Insert joined and transformed data into ORDERSUMMARY
---------------------------------------------------------

-- Insert joined customer-order records with computed TOTALAMOUNT into ORDERSUMMARY
-- Purpose: Enrich order data with customer name and calculate line-level spend for downstream aggregation
INSERT INTO IDEA_2_DB.PUBLIC.ORDERSUMMARY (
    ORDERID,
    CUSTID,
    NAME,
    ITEMNAME,
    PRICEPERUNIT,
    QTY,
    TOTALAMOUNT,
    ORDER_DATE,
    STARTDATE,
    ENDDATE,
    ISACTIVE
)
SELECT
    O.ORDERID,
    O.CUSTID,
    C.NAME,
    O.ITEMNAME,
    O.PRICEPERUNIT,
    O.QTY,
    (O.PRICEPERUNIT * O.QTY)  AS TOTALAMOUNT,
    O.ORDER_DATE,
    O.STARTDATE,
    O.ENDDATE,
    O.ISACTIVE
FROM IDEA_2_DB.PUBLIC."order"  O
INNER JOIN IDEA_2_DB.PUBLIC.CUSTOMER C
    ON O.CUSTID = C.CUSTID;