/*==============================================================
Object Name    : TRANSFORM_SCD2
Purpose        : Apply SCD Type 2 logic to CUSTOMER_SCD2 table
                 using a MERGE statement. Expire changed records
                 and insert new versions; insert brand-new customers
                 directly. Maintains full historical lineage of
                 customer attribute changes.
Generated By   : SDLC_DEVELOPER
==============================================================*/

---------------------------------------------------------
-- SECTION 1
-- Purpose: MERGE CUSTOMER changes into CUSTOMER_SCD2 (SCD Type 2)
---------------------------------------------------------

-- Merge current CUSTOMER records into CUSTOMER_SCD2 to implement SCD Type 2 history
-- Purpose: Detect new and changed customer records; expire old versions and insert new versions;
--          insert brand-new customers as active records with today as EFFECTIVE_FROM
MERGE INTO IDEA_2_DB.PUBLIC.CUSTOMER_SCD2  TGT
USING (
    SELECT
        CUSTID,
        NAME,
        EMAILID,
        REGION
    FROM IDEA_2_DB.PUBLIC.CUSTOMER
) SRC
ON (
    TGT.CUSTID     = SRC.CUSTID
    AND TGT.IS_CURRENT = TRUE
)
WHEN MATCHED AND (
        TGT.NAME    <> SRC.NAME
     OR TGT.EMAILID <> SRC.EMAILID
     OR TGT.REGION  <> SRC.REGION
)
THEN UPDATE SET
    TGT.IS_CURRENT   = FALSE,
    TGT.EFFECTIVE_TO = CURRENT_DATE()
WHEN NOT MATCHED THEN
INSERT (
    CUSTID,
    NAME,
    EMAILID,
    REGION,
    IS_CURRENT,
    EFFECTIVE_FROM,
    EFFECTIVE_TO
)
VALUES (
    SRC.CUSTID,
    SRC.NAME,
    SRC.EMAILID,
    SRC.REGION,
    TRUE,
    CURRENT_DATE(),
    NULL
);

---------------------------------------------------------
-- SECTION 2
-- Purpose: Insert new versions for records that were expired in SECTION 1
---------------------------------------------------------

-- Insert new active SCD2 rows for customers whose prior version was just expired
-- Purpose: After expiring changed records via MERGE UPDATE, create the new current version
--          so that CUSTOMER_SCD2 always has an IS_CURRENT=TRUE row for every active customer
INSERT INTO IDEA_2_DB.PUBLIC.CUSTOMER_SCD2 (
    CUSTID,
    NAME,
    EMAILID,
    REGION,
    IS_CURRENT,
    EFFECTIVE_FROM,
    EFFECTIVE_TO
)
SELECT
    SRC.CUSTID,
    SRC.NAME,
    SRC.EMAILID,
    SRC.REGION,
    TRUE,
    CURRENT_DATE(),
    NULL
FROM IDEA_2_DB.PUBLIC.CUSTOMER  SRC
WHERE EXISTS (
    SELECT 1
    FROM IDEA_2_DB.PUBLIC.CUSTOMER_SCD2  HIST
    WHERE HIST.CUSTID        = SRC.CUSTID
      AND HIST.IS_CURRENT    = FALSE
      AND HIST.EFFECTIVE_TO  = CURRENT_DATE()
)
AND NOT EXISTS (
    SELECT 1
    FROM IDEA_2_DB.PUBLIC.CUSTOMER_SCD2  CURR
    WHERE CURR.CUSTID     = SRC.CUSTID
      AND CURR.IS_CURRENT = TRUE
);