/*=========================================================
Object Name : DDL_AEROSPACE_PARTS_TARGET
Purpose     : Target table DDL
Author      : SDLC_AGENT
Generated By: SDLC_AGENT
=========================================================*/

USE WAREHOUSE SNOWFLAKE_LEARNING_WH;
USE DATABASE GEN_AI_POC_SNOWFLAKECOE;
USE SCHEMA SDLC_WIZARD;

-- SECTION 1: Object Definition
CREATE TABLE IF NOT EXISTS AEROSPACE_PARTS_TARGET (
    PART_NUMBER             VARCHAR(50)     NOT NULL,
    MANUFACTURER            VARCHAR(100),
    WEIGHT_KG               NUMBER(10,4),
    UNIT_PRICE_USD          NUMBER(15,2),
    LIFECYCLE_STATUS        VARCHAR(50),
    INSTALLATION_DATE       DATE,
    CERTIFICATION_STATUS    VARCHAR(50),
    LEAD_TIME_DAYS          NUMBER(6,0),
    RISK_SCORE              VARCHAR(20),
    IS_DECOMMISSIONED       BOOLEAN         DEFAULT FALSE,
    DW_CREATED_AT           TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    DW_UPDATED_AT           TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT              TIMESTAMP_NTZ
);

-- SECTION 2: Constraints
ALTER TABLE AEROSPACE_PARTS_TARGET
    ADD CONSTRAINT IF NOT EXISTS PK_APT_PART_NUMBER PRIMARY KEY (PART_NUMBER);

-- SECTION 3: Notes
-- SCD Type      : 1 (upsert; history not retained)
-- Business Key  : PART_NUMBER
-- Derived Col   : RISK_SCORE = HIGH/MEDIUM/LOW based on CERTIFICATION_STATUS + LEAD_TIME_DAYS
-- Soft Delete   : IS_DECOMMISSIONED flag set TRUE for decommissioned records
-- Exclusion     : LIFECYCLE_STATUS='End of Life' AND INSTALLATION_DATE < DATEADD(year,-3,CURRENT_DATE)