/*=========================================================
Object Name : DDL_ETL_RECONCILIATION_LOG
Purpose     : ETL reconciliation log DDL
Author      : SDLC_AGENT
Generated By: SDLC_AGENT
=========================================================*/

USE WAREHOUSE SNOWFLAKE_LEARNING_WH;
USE DATABASE GEN_AI_POC_SNOWFLAKECOE;
USE SCHEMA SDLC_WIZARD;

-- SECTION 1: Object Definition
CREATE TABLE IF NOT EXISTS ETL_RECONCILIATION_LOG (
    RUN_ID                  VARCHAR(100)    NOT NULL,
    RUN_TIMESTAMP           TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_COUNT            NUMBER(15,0),
    FILTERED_COUNT          NUMBER(15,0),
    DEDUPLICATED_COUNT      NUMBER(15,0),
    INSERTED_COUNT          NUMBER(15,0),
    UPDATED_COUNT           NUMBER(15,0),
    SOFT_DELETED_COUNT      NUMBER(15,0),
    WATERMARK_FROM          TIMESTAMP_NTZ,
    WATERMARK_TO            TIMESTAMP_NTZ,
    STATUS                  VARCHAR(20),
    ERROR_MESSAGE           VARCHAR(4000),
    EXECUTION_TIME_SECS     NUMBER(10,2)
);

-- SECTION 2: Constraints
ALTER TABLE ETL_RECONCILIATION_LOG
    ADD CONSTRAINT IF NOT EXISTS PK_ERL_RUN_ID PRIMARY KEY (RUN_ID);

-- SECTION 3: Notes
-- Populated by : SP_LOAD_AEROSPACE_PARTS_SCD1
-- One row per  : Pipeline execution run
-- Status values: SUCCESS | FAILED | PARTIAL
-- Retention    : All runs retained for audit / compliance traceability