/*=========================================================
Object Name : SP_LOAD_AEROSPACE_PARTS_SCD1
Purpose     : Main pipeline stored procedure
Author      : SDLC_AGENT
Generated By: SDLC_AGENT
=========================================================*/

CREATE OR REPLACE PROCEDURE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_ETL()
RETURNS VARCHAR
LANGUAGE SQL
WAREHOUSE = SNOWFLAKE_LEARNING_WH
AS
$$
-- SECTION 1: Variables

    -- Run tracking variables
    v_run_id            VARCHAR;
    v_run_timestamp     TIMESTAMP_NTZ;
    v_watermark_-- SECTION 2: Source Processing
from    TIMESTAMP_NTZ;
    v_watermark_to      TIMESTAMP_NTZ;

    -- Reconciliation counters
    v_source_count      INTEGER DEFAULT 0;
    v_filtered_count    INTEGER DEFAULT 0;
    v_deduplicated_count INTEGER DEFAULT 0;
    v_inserted_count    INTEGER DEFAULT 0;
    v_updated_count     INTEGER DEFAULT 0;
    v_soft_deleted_count INTEGER DEFAULT 0;

    -- Timing
    v_start_time        TIMESTAMP_NTZ;
    v_end_time          TIMESTAMP_NTZ;
    v_execution_secs    FLOAT DEFAULT 0;

    -- Status tracking
    v_status            VARCHAR DEFAULT 'SUCCESS';
    v_error_message     VARCHAR DEFAULT NULL;

    -- Result
    v_result            VARCHAR;

BEGIN
    ------------------------------------------------------------
    -- 1. INITIALISE RUN METADATA
    ------------------------------------------------------------
    v_run_id        := GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_ETL.name
                       || '_' || TO_VARCHAR(CURRENT_TIMESTAMP(), 'YYYYMMDD_HH24MISS');
    v_run_timestamp := CURRENT_TIMESTAMP()::TIMESTAMP_NTZ;
    v_start_time    := CURRENT_TIMESTAMP()::TIMESTAMP_NTZ;

    ------------------------------------------------------------
    -- 2. DETERMINE WATERMARK WINDOW
    --    FROM  = last successful WATERMARK_TO (or epoch -- SECTION 3: Data Validation
if none)
    --    TO    = current timestamp
    ------------------------------------------------------------
    SELECT COALESCE(MAX(WATERMARK_TO), '1900-01-01 00:00:00'::TIMESTAMP_NTZ)
    INTO   v_watermark_from
    FROM   GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG
    WHERE  STATUS = 'SUCCESS';

    v_watermark_to := v_start_time;

    ------------------------------------------------------------
    -- 3. STAGE INCREMENTAL SOURCE DATA
    --    Filter rows updated since the last successful run.
    --    Deduplicate within the batch keeping the latest record
    --    per PART_NUMBER.
    ------------------------------------------------------------
    CREATE OR REPLACE TEMPORARY TABLE SDLC_WIZARD.TMP_AEROSPACE_STAGED AS
    WITH raw_incremental AS (
        SELECT
            PART_NUMBER,
            MANUFACTURER,
            CERTIFICATION_STATUS,
            INSTALLATION_DATE,
            LEAD_TIME_DAYS,
            LIFECYCLE_STATUS,
            UNIT_PRICE_USD,
            UPDATED_AT,
            WEIGHT_KG,
            CREATED_AT,
            ROW_NUMBER() OVER (
                PARTITION BY PART_NUMBER
                ORDER BY     UPDATED_AT DESC, CREATED_AT DESC
            ) AS rn
        FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE
        WHERE UPDATED_AT >  v_watermark_from
          AND UPDATED_AT <= v_watermark_to
    )
    SELECT
        PART_NUMBER,
        MANUFACTURER,
        CERTIFICATION_STATUS,
        INSTALLATION_DATE,
        LEAD_TIME_DAYS,
        LIFECYCLE_STATUS,
        UNIT_PRICE_USD,
        UPDATED_AT,
        WEIGHT_KG,
        CREATED_AT
    FROM raw_incremental
    WHERE rn = 1;

    ------------------------------------------------------------
    -- 4. CAPTURE SOURCE & DEDUP COUNTS
    ------------------------------------------------------------
    SELECT COUNT(*)
    INTO   v_source_count
    FROM   GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE
    WHERE  UPDATED_AT >  v_watermark_from
      AND  UPDATED_AT <= v_watermark_to;

    SELECT COUNT(*)
    INTO   v_deduplicated_count
    FROM   SDLC_WIZARD.TMP_AEROSPACE_STAGED;

    -- Rows removed during deduplication
    v_filtered_count := v_source_count - v_deduplicated_count;

    ------------------------------------------------------------
    -- 5. APPLY DATA-QUALITY FILTER
    --    Reject rows missing mandatory business keys.
    --    (Filtered_count accumulates; only clean rows proceed.)
    ------------------------------------------------------------
    CREATE OR REPLACE TEMPORARY TABLE SDLC_WIZARD.TMP_AEROSPACE_CLEAN AS
    SELECT *
    FROM   SDLC_WIZARD.TMP_AEROSPACE_STAGED
    WHERE  PART_NUMBER   IS NOT NULL
      AND  MANUFACTURER  IS NOT NULL
      AND  LIFECYCLE_STATUS IS NOT NULL;

    -- Add any DQ-rejected rows to filtered_count
    v_filtered_count := v_filtered_count
                        + (v_deduplicated_count
                           - (SELECT COUNT(*) FROM SDLC_WIZARD.TMP_AEROSPACE_CLEAN));

    -- Refresh deduplicated_count to reflect only clean rows
    SELECT COUNT(*)
    INTO   v_deduplicated_count
    FROM   SDLC_WIZARD.TMP_AEROSPACE_CLEAN;

    ------------------------------------------------------------
    -- 6. DERIVE RISK_SCORE
    --    Scoring logic (additive, capped at 100):
    --      • CERTIFICATION_STATUS = 'EXPIRED'       → +40
    --      • CERTIFICATION_STATUS = 'PENDING'        → +20
    --      • CERTIFICATION_STATUS = 'CONDITIONAL'    → +10
    --      • LEAD_TIME_DAYS > 90                     → +30
    --      • LEAD_TIME_DAYS BETWEEN 45 AND 90        → +15
    --      • LIFECYCLE_STATUS IN ('END_OF_LIFE',
    --                             'DECOMMISSIONED')  → +30
    --      • LIFECYCLE_STATUS = 'CRITICAL'           → +15
    ------------------------------------------------------------
    CREATE OR REPLACE TEMPORARY TABLE SDLC_WIZARD.TMP_AEROSPACE_ENRICHED AS
    SELECT
        PART_NUMBER,
        MANUFACTURER,
        CERTIFICATION_STATUS,
        INSTALLATION_DATE,
        LEAD_TIME_DAYS,
        LIFECYCLE_STATUS,
        UNIT_PRICE_USD,
        UPDATED_AT,
        WEIGHT_KG,
        -- Derived RISK_SCORE (capped at 100)
        LEAST(
            COALESCE(
                CASE CERTIFICATION_STATUS
                    WHEN 'EXPIRED'     THEN 40
                    WHEN 'PENDING'     THEN 20
                    WHEN 'CONDITIONAL' THEN 10
                    ELSE                    0
                END, 0)
            + COALESCE(
                CASE
                    WHEN LEAD_TIME_DAYS > 90               THEN 30
                    WHEN LEAD_TIME_DAYS BETWEEN 45 AND 90  THEN 15
                    ELSE                                        0
                END, 0)
            + COALESCE(
                CASE
                    WHEN LIFECYCLE_STATUS IN ('END_OF_LIFE','DECOMMISSIONED') THEN 30
                    WHEN LIFECYCLE_STATUS = 'CRITICAL'                        THEN 15
                    ELSE                                                            0
                END, 0),
            100
        ) AS RISK_SCORE,
        -- Soft-delete flag: mark DECOMMISSIONED parts
        CASE
            WHEN LIFECYCLE_STATUS = 'DECOMMISSIONED' THEN TRUE
            ELSE FALSE
        END AS IS_DECOMMISSIONED
    FROM SDLC_WIZARD.TMP_AEROSPACE_CLEAN;

    ------------------------------------------------------------
    -- 7. SCD TYPE 1 -- SECTION 4: Merge Logic
MERGE INTO TARGET
    ------------------------------------------------------------
    MERGE INTO GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET  AS tgt
    USING      SDLC_WIZARD.TMP_AEROSPACE_ENRICHED                           AS src
        ON tgt.PART_NUMBER = src.PART_NUMBER

    -- UPDATE existing record (SCD Type 1 overwrite)
    WHEN MATCHED AND (
            tgt.MANUFACTURER          <> src.MANUFACTURER          OR
            tgt.CERTIFICATION_STATUS  <> src.CERTIFICATION_STATUS  OR
            tgt.INSTALLATION_DATE     IS DISTINCT FROM src.INSTALLATION_DATE OR
            tgt.LEAD_TIME_DAYS        <> src.LEAD_TIME_DAYS        OR
            tgt.LIFECYCLE_STATUS      <> src.LIFECYCLE_STATUS      OR
            tgt.UNIT_PRICE_USD        <> src.UNIT_PRICE_USD        OR
            tgt.WEIGHT_KG             <> src.WEIGHT_KG             OR
            tgt.UPDATED_AT            <> src.UPDATED_AT
        )
    THEN UPDATE SET
        tgt.MANUFACTURER         = src.MANUFACTURER,
        tgt.CERTIFICATION_STATUS = src.CERTIFICATION_STATUS,
        tgt.INSTALLATION_DATE    = src.INSTALLATION_DATE,
        tgt.LEAD_TIME_DAYS       = src.LEAD_TIME_DAYS,
        tgt.LIFECYCLE_STATUS     = src.LIFECYCLE_STATUS,
        tgt.UNIT_PRICE_USD       = src.UNIT_PRICE_USD,
        tgt.WEIGHT_KG            = src.WEIGHT_KG,
        tgt.UPDATED_AT           = src.UPDATED_AT,
        tgt.RISK_SCORE           = src.RISK_SCORE,
        tgt.IS_DECOMMISSIONED    = src.IS_DECOMMISSIONED,
        tgt.DW_UPDATED_AT        = CURRENT_TIMESTAMP()::TIMESTAMP_NTZ

    -- INSERT new record
    WHEN NOT MATCHED THEN INSERT (
        PART_NUMBER,
        MANUFACTURER,
        CERTIFICATION_STATUS,
        INSTALLATION_DATE,
        LEAD_TIME_DAYS,
        LIFECYCLE_STATUS,
        UNIT_PRICE_USD,
        UPDATED_AT,
        WEIGHT_KG,
        RISK_SCORE,
        IS_DECOMMISSIONED,
        DW_CREATED_AT,
        DW_UPDATED_AT
    )
    VALUES (
        src.PART_NUMBER,
        src.MANUFACTURER,
        src.CERTIFICATION_STATUS,
        src.INSTALLATION_DATE,
        src.LEAD_TIME_DAYS,
        src.LIFECYCLE_STATUS,
        src.UNIT_PRICE_USD,
        src.UPDATED_AT,
        src.WEIGHT_KG,
        src.RISK_SCORE,
        src.IS_DECOMMISSIONED,
        CURRENT_TIMESTAMP()::TIMESTAMP_NTZ,
        CURRENT_TIMESTAMP()::TIMESTAMP_NTZ
    );

    ------------------------------------------------------------
    -- 8. CAPTURE MERGE RESULT COUNTS
    --    Snowflake does not expose per-action row counts from
    --    MERGE directly in SQL variables, so we derive them
    --    from the target post-merge reconciliation.
    ------------------------------------------------------------
    -- Approximate inserted vs updated from the enriched stage:
    SELECT
        SUM(CASE WHEN tgt_chk.DW_CREATED_AT >= v_start_time THEN 1 ELSE 0 END),
        SUM(CASE WHEN tgt_chk.DW_UPDATED_AT >= v_start_time
                  AND tgt_chk.DW_CREATED_AT  <  v_start_time THEN 1 ELSE 0 END)
    INTO v_inserted_count, v_updated_count
    FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET AS tgt_chk
    WHERE tgt_chk.PART_NUMBER IN (SELECT PART_NUMBER FROM SDLC_WIZARD.TMP_AEROSPACE_ENRICHED);

    -- Soft-deleted (DECOMMISSIONED) rows processed this run
    SELECT COUNT(*)
    INTO   v_soft_deleted_count
    FROM   SDLC_WIZARD.TMP_AEROSPACE_ENRICHED
    WHERE  IS_DECOMMISSIONED = TRUE;

    ------------------------------------------------------------
    -- 9. CAPTURE EXECUTION TIME
    ------------------------------------------------------------
    v_end_time       := CURRENT_TIMESTAMP()::TIMESTAMP_NTZ;
    v_execution_secs := DATEDIFF('millisecond', v_start_time, v_end_time) / 1000.0;

    ------------------------------------------------------------
    -- 10. WRITE RECONCILIATION LOG (SUCCESS)
    --     Column list strictly matches ETL_RECONCILIATION_LOG DDL:
    --     RUN_ID, RUN_TIMESTAMP, STATUS, ERROR_MESSAGE,
    --     SOURCE_COUNT, FILTERED_COUNT, DEDUPLICATED_COUNT,
    --     INSERTED_COUNT, UPDATED_COUNT, SOFT_DELETED_COUNT,
    --     EXECUTION_TIME_SECS, WATERMARK_FROM, WATERMARK_TO
    ------------------------------------------------------------
    -- SECTION 5: Reconciliation
INSERT INTO GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG (
        RUN_ID,
        RUN_TIMESTAMP,
        STATUS,
        ERROR_MESSAGE,
        SOURCE_COUNT,
        FILTERED_COUNT,
        DEDUPLICATED_COUNT,
        INSERTED_COUNT,
        UPDATED_COUNT,
        SOFT_DELETED_COUNT,
        EXECUTION_TIME_SECS,
        WATERMARK_FROM,
        WATERMARK_TO
    )
    VALUES (
        v_run_id,
        v_run_timestamp,
        v_status,
        v_error_message,
        v_source_count,
        v_filtered_count,
        v_deduplicated_count,
        v_inserted_count,
        v_updated_count,
        v_soft_deleted_count,
        v_execution_secs,
        v_watermark_from,
        v_watermark_to
    );

    ------------------------------------------------------------
    -- 11. RETURN SUCCESS SUMMARY
    ------------------------------------------------------------
    v_result := OBJECT_CONSTRUCT(
        'run_id',             v_run_id,
        'status',             v_status,
        'watermark_from',     TO_VARCHAR(v_watermark_from),
        'watermark_to',       TO_VARCHAR(v_watermark_to),
        'source_count',       v_source_count,
        'filtered_count',     v_filtered_count,
        'deduplicated_count', v_deduplicated_count,
        'inserted_count',     v_inserted_count,
        'updated_count',      v_updated_count,
        'soft_deleted_count', v_soft_deleted_count,
        'execution_time_secs',v_execution_secs
    )::VARCHAR;

    RETURN v_result;

--------------------------------------------------------------------
-- EXCEPTION HANDLER
--------------------------------------------------------------------
-- SECTION 6: Error Handling
EXCEPTION
    WHEN OTHER THEN
        v_status        := 'FAILED';
        v_error_message := SQLERRM;
        v_end_time      := CURRENT_TIMESTAMP()::TIMESTAMP_NTZ;
        v_execution_secs:= DATEDIFF('millisecond', v_start_time, v_end_time) / 1000.0;

        -- Log the failure
        INSERT INTO GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG (
            RUN_ID,
            RUN_TIMESTAMP,
            STATUS,
            ERROR_MESSAGE,
            SOURCE_COUNT,
            FILTERED_COUNT,
            DEDUPLICATED_COUNT,
            INSERTED_COUNT,
            UPDATED_COUNT,
            SOFT_